/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HumanScoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CO2E_AVOIDED"
      | "DECAY_RATE_BPS_PER_YEAR"
      | "EV_CHARGING"
      | "RENEWABLE_ENERGY"
      | "SECONDS_PER_YEAR"
      | "SUSTAINABLE_PURCHASE"
      | "TIER_A_MULTIPLIER"
      | "TIER_B_MULTIPLIER"
      | "TIER_C_MULTIPLIER"
      | "TREES_PLANTED"
      | "getHumanLevel"
      | "getHumanScore"
      | "getImpactBreakdown"
      | "getProofCountByTier"
      | "humanIdentity"
      | "impactWeights"
      | "meetsThreshold"
      | "proofRegistry"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ImpactWeightUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "CO2E_AVOIDED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DECAY_RATE_BPS_PER_YEAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EV_CHARGING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RENEWABLE_ENERGY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SECONDS_PER_YEAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUSTAINABLE_PURCHASE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_A_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_B_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_C_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREES_PLANTED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHumanLevel",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHumanScore",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getImpactBreakdown",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProofCountByTier",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "humanIdentity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "impactWeights",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "meetsThreshold",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proofRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "CO2E_AVOIDED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DECAY_RATE_BPS_PER_YEAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EV_CHARGING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RENEWABLE_ENERGY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SECONDS_PER_YEAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUSTAINABLE_PURCHASE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_A_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_B_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_C_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREES_PLANTED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHumanLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHumanScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImpactBreakdown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProofCountByTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "humanIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "impactWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "meetsThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proofRegistry",
    data: BytesLike
  ): Result;
}

export namespace ImpactWeightUpdatedEvent {
  export type InputTuple = [impactType: BytesLike, weight: BigNumberish];
  export type OutputTuple = [impactType: string, weight: bigint];
  export interface OutputObject {
    impactType: string;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HumanScore extends BaseContract {
  connect(runner?: ContractRunner | null): HumanScore;
  waitForDeployment(): Promise<this>;

  interface: HumanScoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CO2E_AVOIDED: TypedContractMethod<[], [string], "view">;

  DECAY_RATE_BPS_PER_YEAR: TypedContractMethod<[], [bigint], "view">;

  EV_CHARGING: TypedContractMethod<[], [string], "view">;

  RENEWABLE_ENERGY: TypedContractMethod<[], [string], "view">;

  SECONDS_PER_YEAR: TypedContractMethod<[], [bigint], "view">;

  SUSTAINABLE_PURCHASE: TypedContractMethod<[], [string], "view">;

  TIER_A_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  TIER_B_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  TIER_C_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  TREES_PLANTED: TypedContractMethod<[], [string], "view">;

  getHumanLevel: TypedContractMethod<[humanId: BytesLike], [bigint], "view">;

  getHumanScore: TypedContractMethod<[humanId: BytesLike], [bigint], "view">;

  getImpactBreakdown: TypedContractMethod<
    [humanId: BytesLike, impactType: BytesLike],
    [[bigint, bigint] & { totalValue: bigint; weightedValue: bigint }],
    "view"
  >;

  getProofCountByTier: TypedContractMethod<
    [humanId: BytesLike],
    [
      [bigint, bigint, bigint] & { tierA: bigint; tierB: bigint; tierC: bigint }
    ],
    "view"
  >;

  humanIdentity: TypedContractMethod<[], [string], "view">;

  impactWeights: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  meetsThreshold: TypedContractMethod<
    [humanId: BytesLike, minScore: BigNumberish],
    [boolean],
    "view"
  >;

  proofRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CO2E_AVOIDED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DECAY_RATE_BPS_PER_YEAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EV_CHARGING"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RENEWABLE_ENERGY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SECONDS_PER_YEAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SUSTAINABLE_PURCHASE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TIER_A_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_B_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_C_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREES_PLANTED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getHumanLevel"
  ): TypedContractMethod<[humanId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHumanScore"
  ): TypedContractMethod<[humanId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getImpactBreakdown"
  ): TypedContractMethod<
    [humanId: BytesLike, impactType: BytesLike],
    [[bigint, bigint] & { totalValue: bigint; weightedValue: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProofCountByTier"
  ): TypedContractMethod<
    [humanId: BytesLike],
    [
      [bigint, bigint, bigint] & { tierA: bigint; tierB: bigint; tierC: bigint }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "humanIdentity"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "impactWeights"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "meetsThreshold"
  ): TypedContractMethod<
    [humanId: BytesLike, minScore: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "proofRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ImpactWeightUpdated"
  ): TypedContractEvent<
    ImpactWeightUpdatedEvent.InputTuple,
    ImpactWeightUpdatedEvent.OutputTuple,
    ImpactWeightUpdatedEvent.OutputObject
  >;

  filters: {
    "ImpactWeightUpdated(bytes32,uint256)": TypedContractEvent<
      ImpactWeightUpdatedEvent.InputTuple,
      ImpactWeightUpdatedEvent.OutputTuple,
      ImpactWeightUpdatedEvent.OutputObject
    >;
    ImpactWeightUpdated: TypedContractEvent<
      ImpactWeightUpdatedEvent.InputTuple,
      ImpactWeightUpdatedEvent.OutputTuple,
      ImpactWeightUpdatedEvent.OutputObject
    >;
  };
}
