/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IHumanIdentityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getHumanId"
      | "getWallet"
      | "humanExists"
      | "isRegistered"
      | "linkExternalProof"
      | "registerHuman"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "HumanRegistered" | "IdentityLinked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getHumanId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWallet",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "humanExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "linkExternalProof",
    values: [BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerHuman",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getHumanId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "humanExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "linkExternalProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerHuman",
    data: BytesLike
  ): Result;
}

export namespace HumanRegisteredEvent {
  export type InputTuple = [
    humanId: BytesLike,
    wallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    humanId: string,
    wallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    humanId: string;
    wallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityLinkedEvent {
  export type InputTuple = [
    humanId: BytesLike,
    externalProofHash: BytesLike,
    provider: string
  ];
  export type OutputTuple = [
    humanId: string,
    externalProofHash: string,
    provider: string
  ];
  export interface OutputObject {
    humanId: string;
    externalProofHash: string;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IHumanIdentity extends BaseContract {
  connect(runner?: ContractRunner | null): IHumanIdentity;
  waitForDeployment(): Promise<this>;

  interface: IHumanIdentityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getHumanId: TypedContractMethod<[wallet: AddressLike], [string], "view">;

  getWallet: TypedContractMethod<[humanId: BytesLike], [string], "view">;

  humanExists: TypedContractMethod<[humanId: BytesLike], [boolean], "view">;

  isRegistered: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  linkExternalProof: TypedContractMethod<
    [externalProofHash: BytesLike, provider: string, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  registerHuman: TypedContractMethod<[], [string], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getHumanId"
  ): TypedContractMethod<[wallet: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getWallet"
  ): TypedContractMethod<[humanId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "humanExists"
  ): TypedContractMethod<[humanId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "linkExternalProof"
  ): TypedContractMethod<
    [externalProofHash: BytesLike, provider: string, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerHuman"
  ): TypedContractMethod<[], [string], "nonpayable">;

  getEvent(
    key: "HumanRegistered"
  ): TypedContractEvent<
    HumanRegisteredEvent.InputTuple,
    HumanRegisteredEvent.OutputTuple,
    HumanRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IdentityLinked"
  ): TypedContractEvent<
    IdentityLinkedEvent.InputTuple,
    IdentityLinkedEvent.OutputTuple,
    IdentityLinkedEvent.OutputObject
  >;

  filters: {
    "HumanRegistered(bytes32,address,uint256)": TypedContractEvent<
      HumanRegisteredEvent.InputTuple,
      HumanRegisteredEvent.OutputTuple,
      HumanRegisteredEvent.OutputObject
    >;
    HumanRegistered: TypedContractEvent<
      HumanRegisteredEvent.InputTuple,
      HumanRegisteredEvent.OutputTuple,
      HumanRegisteredEvent.OutputObject
    >;

    "IdentityLinked(bytes32,bytes32,string)": TypedContractEvent<
      IdentityLinkedEvent.InputTuple,
      IdentityLinkedEvent.OutputTuple,
      IdentityLinkedEvent.OutputObject
    >;
    IdentityLinked: TypedContractEvent<
      IdentityLinkedEvent.InputTuple,
      IdentityLinkedEvent.OutputTuple,
      IdentityLinkedEvent.OutputObject
    >;
  };
}
