/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HumanIdentity } from "./HumanIdentity";
export type { HumanScore } from "./HumanScore";
export type { IHumanIdentity } from "./IHumanIdentity";
export type { PoSHNFT } from "./PoSHNFT";
export type { ProofRegistry } from "./ProofRegistry";
