/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ProofRegistry {
  export type ProofStruct = {
    humanId: BytesLike;
    impactType: BytesLike;
    impactValue: BigNumberish;
    methodologyHash: BytesLike;
    verificationHash: BytesLike;
    timestamp: BigNumberish;
    tier: BigNumberish;
  };

  export type ProofStructOutput = [
    humanId: string,
    impactType: string,
    impactValue: bigint,
    methodologyHash: string,
    verificationHash: string,
    timestamp: bigint,
    tier: bigint
  ] & {
    humanId: string;
    impactType: string;
    impactValue: bigint;
    methodologyHash: string;
    verificationHash: string;
    timestamp: bigint;
    tier: bigint;
  };
}

export interface ProofRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedOracles"
      | "getHumanProofCount"
      | "getHumanProofIds"
      | "getProof"
      | "getTotalImpact"
      | "humanIdentity"
      | "humanProofs"
      | "owner"
      | "proofs"
      | "setOracleAuthorization"
      | "submitProof"
      | "totalProofs"
      | "transferOwnership"
      | "usedVerification"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OracleAuthorized"
      | "OwnershipTransferred"
      | "ProofRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedOracles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHumanProofCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHumanProofIds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getProof", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getTotalImpact",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "humanIdentity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "humanProofs",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "proofs", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setOracleAuthorization",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [
      BytesLike,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "totalProofs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedVerification",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedOracles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHumanProofCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHumanProofIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalImpact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "humanIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "humanProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proofs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOracleAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedVerification",
    data: BytesLike
  ): Result;
}

export namespace OracleAuthorizedEvent {
  export type InputTuple = [oracle: AddressLike, authorized: boolean];
  export type OutputTuple = [oracle: string, authorized: boolean];
  export interface OutputObject {
    oracle: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofRegisteredEvent {
  export type InputTuple = [
    humanId: BytesLike,
    proofId: BytesLike,
    impactType: BytesLike,
    impactValue: BigNumberish,
    tier: BigNumberish
  ];
  export type OutputTuple = [
    humanId: string,
    proofId: string,
    impactType: string,
    impactValue: bigint,
    tier: bigint
  ];
  export interface OutputObject {
    humanId: string;
    proofId: string;
    impactType: string;
    impactValue: bigint;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProofRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProofRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedOracles: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getHumanProofCount: TypedContractMethod<
    [humanId: BytesLike],
    [bigint],
    "view"
  >;

  getHumanProofIds: TypedContractMethod<
    [humanId: BytesLike],
    [string[]],
    "view"
  >;

  getProof: TypedContractMethod<
    [proofId: BytesLike],
    [ProofRegistry.ProofStructOutput],
    "view"
  >;

  getTotalImpact: TypedContractMethod<
    [humanId: BytesLike, impactType: BytesLike],
    [bigint],
    "view"
  >;

  humanIdentity: TypedContractMethod<[], [string], "view">;

  humanProofs: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proofs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, string, bigint, bigint] & {
        humanId: string;
        impactType: string;
        impactValue: bigint;
        methodologyHash: string;
        verificationHash: string;
        timestamp: bigint;
        tier: bigint;
      }
    ],
    "view"
  >;

  setOracleAuthorization: TypedContractMethod<
    [oracle: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  submitProof: TypedContractMethod<
    [
      humanId: BytesLike,
      impactType: BytesLike,
      impactValue: BigNumberish,
      methodologyHash: BytesLike,
      verificationHash: BytesLike,
      timestamp: BigNumberish,
      tier: BigNumberish,
      oracleSignature: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  totalProofs: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usedVerification: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedOracles"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getHumanProofCount"
  ): TypedContractMethod<[humanId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHumanProofIds"
  ): TypedContractMethod<[humanId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<
    [proofId: BytesLike],
    [ProofRegistry.ProofStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalImpact"
  ): TypedContractMethod<
    [humanId: BytesLike, impactType: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "humanIdentity"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "humanProofs"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proofs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, string, bigint, bigint] & {
        humanId: string;
        impactType: string;
        impactValue: bigint;
        methodologyHash: string;
        verificationHash: string;
        timestamp: bigint;
        tier: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setOracleAuthorization"
  ): TypedContractMethod<
    [oracle: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [
      humanId: BytesLike,
      impactType: BytesLike,
      impactValue: BigNumberish,
      methodologyHash: BytesLike,
      verificationHash: BytesLike,
      timestamp: BigNumberish,
      tier: BigNumberish,
      oracleSignature: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalProofs"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedVerification"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "OracleAuthorized"
  ): TypedContractEvent<
    OracleAuthorizedEvent.InputTuple,
    OracleAuthorizedEvent.OutputTuple,
    OracleAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProofRegistered"
  ): TypedContractEvent<
    ProofRegisteredEvent.InputTuple,
    ProofRegisteredEvent.OutputTuple,
    ProofRegisteredEvent.OutputObject
  >;

  filters: {
    "OracleAuthorized(address,bool)": TypedContractEvent<
      OracleAuthorizedEvent.InputTuple,
      OracleAuthorizedEvent.OutputTuple,
      OracleAuthorizedEvent.OutputObject
    >;
    OracleAuthorized: TypedContractEvent<
      OracleAuthorizedEvent.InputTuple,
      OracleAuthorizedEvent.OutputTuple,
      OracleAuthorizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProofRegistered(bytes32,bytes32,bytes32,uint256,uint8)": TypedContractEvent<
      ProofRegisteredEvent.InputTuple,
      ProofRegisteredEvent.OutputTuple,
      ProofRegisteredEvent.OutputObject
    >;
    ProofRegistered: TypedContractEvent<
      ProofRegisteredEvent.InputTuple,
      ProofRegisteredEvent.OutputTuple,
      ProofRegisteredEvent.OutputObject
    >;
  };
}
