/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHumanIdentity,
  IHumanIdentityInterface,
} from "../../contracts/IHumanIdentity";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "humanId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "wallet",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "HumanRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "humanId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "externalProofHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "provider",
        type: "string",
      },
    ],
    name: "IdentityLinked",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "getHumanId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "humanId",
        type: "bytes32",
      },
    ],
    name: "getWallet",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "humanId",
        type: "bytes32",
      },
    ],
    name: "humanExists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "isRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "externalProofHash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "provider",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "linkExternalProof",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "registerHuman",
    outputs: [
      {
        internalType: "bytes32",
        name: "humanId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHumanIdentity__factory {
  static readonly abi = _abi;
  static createInterface(): IHumanIdentityInterface {
    return new Interface(_abi) as IHumanIdentityInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHumanIdentity {
    return new Contract(address, _abi, runner) as unknown as IHumanIdentity;
  }
}
