/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HumanIdentity__factory } from "./HumanIdentity__factory";
export { HumanScore__factory } from "./HumanScore__factory";
export { IHumanIdentity__factory } from "./IHumanIdentity__factory";
export { PoSHNFT__factory } from "./PoSHNFT__factory";
export { ProofRegistry__factory } from "./ProofRegistry__factory";
